org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.6
forge_version_range=[47.4.6,48)
loader_version_range=[47,48)
mapping_channel=official
mapping_version=1.20.1
mod_id=villagerhelper
mod_name=村民助手
mod_license=BSD-3-Clause
mod_version=1.0.6
mod_group_id=dev.villagerhelper
mod_authors=666nima
mod_description=独立村民助手：低血好感、最低一个付款物品、全等级原版列表锁定交易、刷新与快速补货
