modLoader="javafml"
loaderVersion="[47,48)"
license="${mod_license}"
[[mods]]
modId="villagerhelper"
version="${mod_version}"
displayName="村民助手"
authors="${mod_authors}"
description='''独立村民助手：好感与折扣、交易刷新、持久化真实未来交易与快速补货。未解锁交易在左侧原版列表灰显，共用滚动，不能购买。补货快捷键默认未绑定。'''
[[dependencies.villagerhelper]]
modId="forge"
mandatory=true
versionRange="[47.4.6,48)"
ordering="NONE"
side="BOTH"
[[dependencies.villagerhelper]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
