modLoader="javafml"
loaderVersion="[47,48)"
license="${mod_license}"
[[mods]]
modId="villagerhelper"
version="${mod_version}"
displayName="村民助手"
authors="${mod_authors}"
description='''全等级真实交易预览与等级锁、从未交易村民刷新、快速补货与交易中升级；原版声望价格和每日自动补货上限'''
[[dependencies.villagerhelper]]
modId="forge"
mandatory=true
versionRange="[47.4.6,48)"
ordering="NONE"
side="BOTH"
[[dependencies.villagerhelper]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
